version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: imdb_user
      POSTGRES_PASSWORD: imdb_pass
      POSTGRES_DB: imdb_db
    ports:
      - "5432:5432"
    volumes:
      - imdb_pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ../.env

volumes:
  imdb_pgdata:
